name: CI Build, Test, and Scan (Simulation)

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run it manually

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 1. Install Build Tools (SIMULATED)
      shell: powershell
      run: |
        Write-Host "Installing BCContainerHelper and AL tools..."
        Start-Sleep -Seconds 5
        Write-Host "Build tools installed."

    - name: 2. Download Dependencies (SIMULATED)
      shell: powershell
      run: |
        Write-Host "Downloading Base Application and System symbols..."
        Start-Sleep -Seconds 5
        Write-Host "Symbols downloaded."

    - name: 3. Compile AL Extension (SIMULATED)
      shell: powershell
      run: |
        Write-Host "Compiling ALProject1/app.json..."
        Start-Sleep -Seconds 5
        Write-Host "Successfully created 'ALProject1.app'."
        
    - name: 4. Run Unit Tests (SIMULATED - Quality Gate #1)
      shell: powershell
      run: |
        Write-Host "Executing 12 Unit Tests..."
        Start-Sleep -Seconds 5
        Write-Host "RESULT: 12 Passed, 0 Failed. (Quality Gate Passed)"
            
    - name: 5. SonarCloud Scan (SIMULATED - Quality Gate #2)
      shell: powershell
      run: |
        Write-Host "Scanning code for maintainability and security..."
        Start-Sleep -Seconds 5
        Write-Host "Quality Gate: PASSED (Coverage 85%, 0 Bugs)."

    - name: 6. Publish Deployable Artifact (SIMULATED)
      shell: powershell
      run: |
        Write-Host "Uploading .app file to artifacts..."
        Start-Sleep -Seconds 2
        Write-Host "Artifact 'BC-Extension-Package' published."
