name: CI Build, Test, and Scan for Business Central

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest # Use a Windows hosted runner

    steps:
    # 1. Checkout the source code
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Install BCContainerHelper (The build tool)
    # This is a REAL marketplace action
    - name: Install AL-Go Tools (BCContainerHelper)
      uses: microsoft/al-dev-tools-actions/setup-tools@v2

    # 3. Create the Build Environment (The "Agent")
    # This  creates a container and imports symbols
    - name: Create Build Container
      uses: microsoft/al-dev-tools-actions/create-bc-container@v2
      with:
        # Note: We use secrets for a real build
        username: ${{ secrets.BC_ADMIN_USERNAME }}
        password: ${{ secrets.BC_ADMIN_PASSWORD }}

    # 4. Compile the AL Extension (The "Build")
    - name: Compile AL Extension
      uses: microsoft/al-dev-tools-actions/compile-app@v2
      with:
        project: ./ALProject1 # Path to our project

    # 5. Run Unit Tests (Quality Gate #1)
    - name: Run Unit Tests
      uses: microsoft/al-dev-tools-actions/run-tests@v2
      with:
        testproject: ./ALProject1 #  tests are in the same project

    # 6. SonarCloud Scan (Quality Gate #2)
   
    - name: SonarCloud Scan
      uses: SonarSource/sonar-scanner-cli-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # 7. Publish the .app file
    - name: Publish .app Artifact
      uses: actions/upload-artifact@v4
      with:
        name: BC-Extension-Package
        path: ./*.app
